# Generated by Django 6.0.7 on 2026-07-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(unique=True, verbose_name='第几天')),
                ('title', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容描述')),
                ('question', models.CharField(default='', max_length=500, verbose_name='打卡问题')),
                ('icon', models.CharField(default='📱', max_length=50, verbose_name='图标')),
            ],
            options={
                'verbose_name': '每日主题',
                'verbose_name_plural': '每日主题',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(default='register', max_length=20, verbose_name='用途')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('avatar', models.CharField(default='', max_length=200, verbose_name='头像')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='第几天')),
                ('date', models.DateField(auto_now_add=True, verbose_name='打卡日期')),
                ('answer', models.TextField(blank=True, default='', verbose_name='回答内容')),
                ('mood', models.CharField(default='😊', max_length=50, verbose_name='心情')),
                ('is_completed', models.BooleanField(default=True, verbose_name='已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'ordering': ['day'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
