# Generated by Django 6.0.7 on 2026-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinrecord',
            options={'ordering': ['-day'], 'verbose_name': '打卡记录', 'verbose_name_plural': '打卡记录'},
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='设备信息'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='用户代理'),
        ),
    ]
