# Generated by Django 6.0.7 on 2026-07-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0002_alter_checkinrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='online_activities',
            field=models.TextField(blank=True, default='', verbose_name='主要上网活动'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='online_duration',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='今日上网时长'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='online_impact',
            field=models.TextField(blank=True, default='', verbose_name='上网带来影响'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='answer',
            field=models.TextField(blank=True, default='', verbose_name='主题回答'),
        ),
    ]
