# Generated by Django 6.0.7 on 2026-07-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0004_message_likes_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(default='', max_length=20, verbose_name='年级'),
        ),
    ]
