# Generated by Django 6.0.7 on 2026-07-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='对应天数')),
                ('question', models.TextField(verbose_name='题目')),
                ('option_a', models.CharField(max_length=200, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=200, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=200, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=200, verbose_name='选项D')),
                ('answer', models.CharField(max_length=1, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='答案解析')),
            ],
            options={
                'verbose_name': '测评题目',
                'verbose_name_plural': '测评题目',
                'ordering': ['day', 'id'],
            },
        ),
    ]
