# Generated by Django 6.0.7 on 2026-07-10 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0007_quiz_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='对应天数')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('correct_count', models.IntegerField(verbose_name='正确题数')),
                ('total_count', models.IntegerField(verbose_name='总题数')),
                ('answers', models.JSONField(verbose_name='答题详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'ordering': ['-day', '-created_at'],
            },
        ),
    ]
