# Generated by Django 6.0.7 on 2026-07-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0008_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_operations', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_reason',
            field=models.TextField(blank=True, default='', verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_status',
            field=models.CharField(choices=[('unverified', '未认证'), ('pending', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='unverified', max_length=20, verbose_name='实名认证状态'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='学校'),
        ),
    ]
