# Generated by Django 6.0.7 on 2026-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0009_userprofile_auth_operator_userprofile_auth_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('admin', '普通管理员'), ('super_admin', '超级管理员')], default='user', max_length=20, verbose_name='角色'),
        ),
    ]
