# Generated by Django 6.0.7 on 2026-07-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0010_add_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_school',
            field=models.CharField(blank=True, default='', help_text='普通管理员负责的学校（仅role=admin时有效）', max_length=100, verbose_name='管理学校'),
        ),
    ]
