# Generated by Django 6.0.7 on 2026-07-11 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0011_add_managed_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('n_type', models.CharField(choices=[('announcement', '官方公告'), ('reminder', '活动提醒'), ('system', '系统通知')], default='announcement', max_length=20, verbose_name='类型')),
                ('target_school', models.CharField(blank=True, help_text='为空则发送给所有学校', max_length=100, verbose_name='目标学校')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='接收人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
    ]
