# Generated by Django 6.0.7 on 2026-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day21', '0012_add_announcement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='q_type',
            field=models.CharField(choices=[('choice', '选择题'), ('true_false', '判断题')], default='choice', max_length=20, verbose_name='题型'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(default='', max_length=200, verbose_name='选项A'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(default='', max_length=200, verbose_name='选项B'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='选项D'),
        ),
    ]
